#install.packages("writexl", repos = "https://cloud.r-project.org" )
#install.packages('openxlsx',repos ='https://cloud.r-project.org' )
#install.packages("feather",repos ='https://cloud.r-project.org' )
#install.packages("SmartEDA",repos ='https://cloud.r-project.org' )
#install.packages("devtools",repos ='https://cloud.r-project.org' )
#install.packages("ggthemes",repos ='https://cloud.r-project.org' )
#install.packages("Metrics",repos ='https://cloud.r-project.org' )
#install.packages("timeSeries",repos ='https://cloud.r-project.org' )
#install.packages("tseries",repos ='https://cloud.r-project.org' )
#install.packages("forecast",repos ='https://cloud.r-project.org' )
#install.packages("prophet",repos ='https://cloud.r-project.org' )
#install.packages("caret",repos ='https://cloud.r-project.org' )
#devtools::install_github('bbc/bbplot')
#install.packages("explore")
#install.packages("purrr")
#library(purrr)
#library(explore)
#library(feather)
library(generics)
library(openxlsx) 
library(ggplot2)
library(tidyr)
library(readxl)
library(dplyr)
library(janitor)
library(tidyverse)
library(str2str)
library(conflicted)
library(rlang)
library(SmartEDA)
library(bbplot)
library(ggthemes)
library(corrplot)
library(timeSeries)
library(tseries)
library(forecast)
library(Metrics)
library(mgcv)
library(prophet)
library(caret)
conflict_prefer('select','dplyr','MASS')
conflict_prefer('filter','dplyr','MASS')
conflict_prefer('filter','dplyr','stats')
conflicts_prefer(dplyr::filter)
